#ifndef BUILD_MACROS_H
#define BUILD_MACROS_H

#define BUILD_TYPE_DEBUG          0
#define BUILD_TYPE_RELEASE        0
#define BUILD_TYPE_RELWITHDEBINFO 0
#define BUILD_TYPE_MINSIZEREL     0

#if defined(DEBUG_BUILD)
    #undef  BUILD_TYPE_DEBUG
    #define BUILD_TYPE_DEBUG 1
#elif defined(RELEASE_BUILD)
    #undef  BUILD_TYPE_RELEASE
    #define BUILD_TYPE_RELEASE 1
#elif defined(RELWITHDEBINFO_BUILD)
    #undef  BUILD_TYPE_RELWITHDEBINFO
    #define BUILD_TYPE_RELWITHDEBINFO 1
#elif defined(MINSIZEREL_BUILD)
    #undef  BUILD_TYPE_MINSIZEREL
    #define BUILD_TYPE_MINSIZEREL 1
#else
    #error "BUILD TYPE UNKNOWN"
#endif

#endif
